Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[25c6ab2] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[f795b18] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[9ff1df2] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[8ba6375] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[457c77c] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in repository() : The 'path' is not in a git repository
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[2e1aefa] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
Error in commit(repo, message = "nuevo") : 
  Error in 'git2r_commit': Nothing added to commit
Ejecuci'on interrumpida
[9fac670] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[d935f94] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[80fd3c5] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[8d12f92] 2021-01-04: nuevo
Error in push(repo) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[8028628] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': Unable to authenticate with supplied credentials
Ejecuci'on interrumpida
[4fbdbf6] 2021-01-04: nuevo
[d494cdf] 2021-01-04: nuevo
[ff26e0b] 2021-01-04: nuevo
[a979dab] 2021-01-04: nuevo
[6ad46c7] 2021-01-04: nuevo
[e277935] 2021-01-04: nuevo
[fb67151] 2021-01-04: nuevo
[385098e] 2021-01-04: nuevo
[7d2b3dd] 2021-01-04: nuevo
[b0429b9] 2021-01-04: nuevo
[338bdbf] 2021-01-04: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': failed to resolve address for github.com: nodename nor servname provided, or not known
Ejecuci'on interrumpida
[d8eefa3] 2021-01-05: nuevo
[bd4e460] 2021-01-05: nuevo
[942b1a6] 2021-01-05: nuevo
[f29bfa7] 2021-01-05: nuevo
[f4f3162] 2021-01-05: nuevo
[6e8cc31] 2021-01-05: nuevo
[9debc7d] 2021-01-05: nuevo
[49a2c76] 2021-01-05: nuevo
[ee8c8ac] 2021-01-05: nuevo
[094dfdb] 2021-01-05: nuevo
[1b67ffe] 2021-01-05: nuevo
[c8238df] 2021-01-05: nuevo
[de1b53e] 2021-01-05: nuevo
[17b15d3] 2021-01-05: nuevo
[c713c39] 2021-01-05: nuevo
Error in add(repo, "*") : 
  Error in 'git2r_index_add_all': failed to read file into stream: 
Ejecuci'on interrumpida
[5af2cc7] 2021-01-05: nuevo
[bd038e3] 2021-01-05: nuevo
[5f5e115] 2021-01-05: nuevo
[534c285] 2021-01-05: nuevo
[c71b48b] 2021-01-05: nuevo
[afa0187] 2021-01-05: nuevo
[6132d0a] 2021-01-05: nuevo
[c7b0931] 2021-01-05: nuevo
[b73e60e] 2021-01-05: nuevo
[1e84be2] 2021-01-05: nuevo
Error in push(repo, credentials = cred) : ignoring SIGPIPE signal
Ejecuci'on interrumpida
[6123574] 2021-01-05: nuevo
[8c0169b] 2021-01-05: nuevo
[bb1c170] 2021-01-05: nuevo
[0af8465] 2021-01-05: nuevo
[7750784] 2021-01-05: nuevo
[08a45d5] 2021-01-05: nuevo
[f2bd02b] 2021-01-05: nuevo
[3c73fd8] 2021-01-05: nuevo
[08ddec7] 2021-01-06: nuevo
[42d16e5] 2021-01-06: nuevo
[ebc7fe4] 2021-01-06: nuevo
[663161b] 2021-01-06: nuevo
[f072a8e] 2021-01-06: nuevo
[70be886] 2021-01-06: nuevo
[fddc8b3] 2021-01-06: nuevo
[5a88f0e] 2021-01-06: nuevo
[a5a8ddc] 2021-01-06: nuevo
Error in push(repo, credentials = cred) : 
  Error in 'git2r_push': failed to resolve address for github.com: nodename nor servname provided, or not known
Ejecuci'on interrumpida
[b396e76] 2021-01-06: nuevo
[0a0ed5e] 2021-01-06: nuevo
